#ifndef CONFIG_H
#define CONFIG_H

#define BLOCK_SIZE (25U)

#define SCREEN_WIDTH (BLOCK_SIZE * SCREEN_WIDTH_BLOCK_CNT)
#define SCREEN_HEIGHT (BLOCK_SIZE * SCREEN_HEIGHT_BLOCK_CNT)
#define SCREEN_WIDTH_BLOCK_CNT (25U)
#define SCREEN_HEIGHT_BLOCK_CNT (15U)

#endif