#ifndef CONFIG_H
#define CONFIG_H

#define BLOCK_SIZE (50U)
#define SCREEN_WIDTH (BLOCK_SIZE * SCREEN_WIDTH_BLOCK_CNT)
#define SCREEN_HEIGHT (BLOCK_SIZE * SCREEN_HEIGHT_BLOCK_CNT)
#define SCREEN_WIDTH_BLOCK_CNT (25U)
#define SCREEN_HEIGHT_BLOCK_CNT (15U)

#define SNAKE_UPDATE_TIMEOUT_SEC (0.2f)

#define SNAKE_GRID_LEN (SCREEN_WIDTH_BLOCK_CNT * SCREEN_HEIGHT_BLOCK_CNT / 2U)
#endif /* CONFIG_H */